---
- name: install zip, unzip and utils
  dnf:
    name: 
      - dnf-utils
      - zip
      - unzip
- name: install pip3
  package:
    name: python3-pip
- name: install docker python library
  pip:
    name: docker
- name: add docker repository
  shell: "dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"
- name: install docker-ce
  shell: "dnf install -y docker-ce --nobest"
- name: enable and start docker service
  systemd:
    name: docker.service
    enabled: yes
    state: started
    