---
- name: remove old docker versions (before docker-ce)
  apt:
    pkg:
      - docker
      - docker-engine
      - docker.io
      - conteainerd
      - runc
    state: absent
- name: install packages to allow apt to use HTTPS repositories
  apt:
    update_cache: yes
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
- name: create keyring folder if not already available
  file:
    path: "{{ gpg_key_path }}"
    state: directory
- name: Add docker repository
  block:
    - name: Add docker GPG key
      shell: "curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg | sudo gpg --dearmor -o {{ gpg_key_path }}/docker.gpg"
    - name: Add docker repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by={{ gpg_key_path }}/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
- name: install docker
  apt:
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
