---
# tasks file for ansible-proxmox-windows-template
- name: modify sshd_config_default
  block:    
    - name: allow password login
      lineinfile:
        path: "{{ temp_subfolder }}/OpenSSH-Win64/sshd_config_default"
        regexp: '#PasswordAuthentication yes'
        line: 'PasswordAuthentication yes'
    - name: remove group match - line 1
      lineinfile:
        path: "{{ temp_subfolder }}/OpenSSH-Win64/sshd_config_default"
        regexp: 'Match Group administrators'
        line: '#Match Group administrators'
    - name: remove group match - line 2
      lineinfile:
        path: "{{ temp_subfolder }}/OpenSSH-Win64/sshd_config_default"
        regexp: '(.+)AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys'
        line: '#AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys'
  become: yes
