---
- name: install packages to allow apt to use HTTPS repositories
  apt:
    update_cache: yes
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
- name: Add gcloud repository
  block:
    - name: Add google cloud SDK repository
      apt_repository:
        repo: "deb https://packages.cloud.google.com/apt cloud-sdk main"
        state: present
    - name: Add google cloud GPG key
      get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /etc/apt/trusted.gpg.d/googlecloud.gpg
- name: install google-cloud-cli
  apt:
    update_cache: yes
    pkg: google-cloud-cli
- name: install additional gcloud components
  apt:
    update_cache: yes
    pkg: "{{ gcloud_cli_additional_components }}"
