---
- name: delete vm if needed
  block:
    - name: stop vm
      shell:
        cmd: "/usr/sbin/qm stop {{ template_vmid }}"
    - name: Wait for vm to be stopped
      shell:
        cmd: "/usr/sbin/qm wait {{ template_vmid }}"    
      async: 180
      poll: 10 
    - name: delete VM
      shell:
        cmd: "/usr/sbin/qm destroy {{ template_vmid }} --purge 1"
    - name: pause for the vm to be deleted
      pause:
        seconds: 30
  become: yes
