---
# tasks file for ansible-linux-basic-setup
- name: edit sshd_config file to enable password login
  replace:
    path: /etc/ssh/sshd_config
    regexp: '(.*)PasswordAuthentication .+'
    replace : '\1PasswordAuthentication yes'
    validate: "/usr/sbin/sshd -T -f %s"
  when: ssh_with_password
- name: edit sshd_config file to disable password login
  replace:
    path: /etc/ssh/sshd_config
    regexp: '(.*)PasswordAuthentication .+'
    replace : '\1PasswordAuthentication no'
    validate: "/usr/sbin/sshd -T -f %s"
  when: not ssh_with_password
- name: restart sshd service
  systemd:
    name: sshd
    state: restarted
