---
# tasks file for ansible-linux-basic-setup
- name: user setup
  block:
    - name: create admin user
      user:
        name: "{{ admin_login }}"
        password: "{{ admin_password }}"
        comment: System administrator
        append: yes
        create_home: yes
        generate_ssh_key: yes
        shell: /bin/bash
    - name: edit sudoers file
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%{{ admin_login }} ALL='
        line: '{{ admin_login }} ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s
